### ISSUE TITLE
Fails when used from an Azure Function

### ISSUE THREAD

**Issue by bittrance** [cloudbase/powershell-yaml#110] opened 2023-06-02 15:28 UTC
Consider a simple Azure Function using powershell-yaml:
```
using namespace System.Net
param($Request)
Import-Module powershell-yaml
Push-OutputBinding -Name Response -Value (@{
        StatusCode = [HttpStatusCode]::OK
        Body = ConvertTo-Yaml @{ "Success" = $true }
    })
```
Given a mocked `Push-OutputBinding`, this function can be executed just fine by Pester. However, trying to executing this function from the Azure Function Powershell worker fails with a number of errors like this one:
```
ERROR: (38,24): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
        return builder.WithEventEmitter(next => new StringQuotingEmitter(next));
                       ^


Exception             :
    Type    : System.Exception
    Message : (38,24): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
              return builder.WithEventEmitter(next => new StringQuotingEmitter(next));
              ^

    HResult : -2146233088
TargetObject          : (38,24): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
CategoryInfo          : InvalidData: ((38,24): error CS00…=cc7b13ffcd2ddd51'.:CSDiagnostic) [Add-Type], Exception
FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
InvocationInfo        :
    MyCommand        : Add-Type
    ScriptLineNumber : 376
    OffsetInLine     : 9
    HistoryId        : 1
    ScriptName       : C:\home\data\ManagedDependencies\2306021425394364036.r\powershell-yaml\0.4.7\powershell-yaml.psm1
    Line             :         Add-Type -TypeDefinition $stringQuotingEmitterSource -ReferencedAssemblies $referenceList -Language CSharp -CompilerOptions "-nowarn:1701"

    PositionMessage  : At C:\home\data\ManagedDependencies\2306021425394364036.r\powershell-yaml\0.4.7\powershell-yaml.psm1:376 char:9
                       +         Add-Type -TypeDefinition $stringQuotingEmitterSource -Referen …
                       +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\home\data\ManagedDependencies\2306021425394364036.r\powershell-yaml\0.4.7
    PSCommandPath    : C:\home\data\ManagedDependencies\2306021425394364036.r\powershell-yaml\0.4.7\powershell-yaml.psm1
    InvocationName   : Add-Type
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\home\data\ManagedDependencies\2306021425394364036.r\powershell-yaml\0.4.7\powershell-yaml.psm1: line 376
                        at <ScriptBlock>, C:\home\site\wwwroot\HelloWorld\Function.ps1: line 5
PipelineIterationInfo :
```
There are similar errors complaining about `Type`, `Enum` and `MulticastDelegate`.

This failure occurs both when run locally, by `func host start` and when published to Azure.

Is this a "real" defect, or is it simply a documentation issue in that I need to include additional dependencies not available "inside" the worker?

**Comment by gabriel-samfira** [comment] 2023-06-02 16:35
Hi @bittrance 

I tried to run this locally in VSCode. Followed the guide here: https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-powershell

I got a huge nr of errors, some like the one you pointed out. But the first one was:

```powershell
[2023-06-02T16:30:47.854Z] Worker process started and initialized.
[2023-06-02T16:30:51.789Z] Host lock lease acquired by instance ID '000000000000000000000000297420BE'.
[2023-06-02T16:30:58.110Z] Executing 'Functions.HttpTrigger1' (Reason='This function was programmatically called via the host APIs.', Id=020aa55f-7303-4807-aa68-b110816ca439)
[2023-06-02T16:30:58.822Z] ERROR: Exception calling "GetFiles" with "3" argument(s): "Could not find a part of the path '/usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/runtimes/unix/lib/net6.0/ref'."
[2023-06-02T16:30:58.822Z] 
[2023-06-02T16:30:58.822Z] Exception             : 
[2023-06-02T16:30:58.822Z]     Type           : System.Management.Automation.MethodInvocationException
[2023-06-02T16:30:58.822Z]     ErrorRecord    : 
[2023-06-02T16:30:58.822Z]         Exception             : 
[2023-06-02T16:30:58.822Z]             Type    : System.Management.Automation.ParentContainsErrorRecordException
[2023-06-02T16:30:58.822Z]             Message : Exception calling "GetFiles" with "3" argument(s): "Could not find a part of the path '/usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/runtimes/unix/lib/net6.0/ref'."
[2023-06-02T16:30:58.822Z]             HResult : -2146233087
[2023-06-02T16:30:58.822Z]         CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
[2023-06-02T16:30:58.822Z]         FullyQualifiedErrorId : DirectoryNotFoundException
[2023-06-02T16:30:58.823Z]         InvocationInfo        : 
[2023-06-02T16:30:58.823Z]             ScriptLineNumber : 375
[2023-06-02T16:30:58.823Z]             OffsetInLine     : 9
[2023-06-02T16:30:58.823Z]             HistoryId        : -1
[2023-06-02T16:30:58.823Z]             ScriptName       : /home/gabriel/.local/share/powershell/Modules/powershell-yaml/0.4.7/powershell-yaml.psm1
[2023-06-02T16:30:58.823Z]             Line             : $referenceList += [IO.Directory]::GetFiles([IO.Path]::Combine($PSHOME, 'ref'), 'netstandard.dll', [IO.SearchOption]::TopDirectoryOnly)
[2023-06-02T16:30:58.823Z]                                
[2023-06-02T16:30:58.823Z]             PositionMessage  : At /home/gabriel/.local/share/powershell/Modules/powershell-yaml/0.4.7/powershell-yaml.psm1:375 char:9
[2023-06-02T16:30:58.823Z]                                +         $referenceList += [IO.Directory]::GetFiles([IO.Path]::Combine …
[2023-06-02T16:30:58.823Z]                                +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2023-06-02T16:30:58.823Z]             PSScriptRoot     : /home/gabriel/.local/share/powershell/Modules/powershell-yaml/0.4.7
[2023-06-02T16:30:58.823Z]             PSCommandPath    : /home/gabriel/.local/share/powershell/Modules/powershell-yaml/0.4.7/powershell-yaml.psm1
[2023-06-02T16:30:58.823Z]             CommandOrigin    : Internal
[2023-06-02T16:30:58.823Z]         ScriptStackTrace      : at <ScriptBlock>, /home/gabriel/.local/share/powershell/Modules/powershell-yaml/0.4.7/powershell-yaml.psm1: line 375
[2023-06-02T16:30:58.823Z]                                 at <ScriptBlock>, /home/gabriel/work/cloudbase/azureFunction/profile.ps1: line 11
```

The interesting bit was:

```powershell
[2023-06-02T16:30:58.822Z] ERROR: Exception calling "GetFiles" with "3" argument(s): "Could not find a part of the path '/usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/runtimes/unix/lib/net6.0/ref'."
```

When I looked for that file:

```bash
gabriel@arrakis:~$ ls /usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/runtimes/unix/lib/net6.0/ref
ls: cannot access '/usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/runtimes/unix/lib/net6.0/ref': No such file or directory
```

I am not sure how to set that path properly (never used azure functions), but I cheated a bit (for the sake of time) by running:

```bash
sudo ln -s /usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/ref /usr/lib/azure-functions-core-tools-4/workers/powershell/7.2/runtimes/unix/lib/net6.0/ref
```

(There is most probably a right way to do this)

After which I could run the function with powershell-yaml and it works.

Stumbled across this: https://github.com/PowerShell/PowerShell/issues/9587

**Comment by gabriel-samfira** [comment] 2023-06-02 17:14
This seems to be a runtime issue. There seem to be missing refs.

**Comment by bittrance** [comment] 2023-06-03 07:15
Thanks for the rapid response :heart:  I can confirm that the `ln` hack works when doing `func host start`. I reported this issue on the worker.

I'll leave it up to you to decide whether you want to keep this issue open for visibility or not.

**Comment by gabriel-samfira** [comment] 2023-06-03 07:17
Happy to help!

The issue will be indexed even if we close it. Most people will probably get here via Google anyway 😄 .

**Closed by gabriel-samfira** 2023-06-03 07:17 UTC

**Comment by mabaumgartner** [comment] 2024-09-26 16:37
I came across this issue as well when attempting to load powershell-yaml in an Azure Automation runbook with the PowerShell7.2 runtime.  

Very similar error message: 
```pwsh
Exception calling "GetFiles" with "3" argument(s): "Could not find a part of the path 'C:\app\runtimes\win\lib\net6.0\ref'.
```

[This comment](https://github.com/Azure/azure-functions-powershell-worker/issues/958#issuecomment-1660821758) might be applicable.

**Comment by gabriel-samfira** [comment] 2024-09-26 16:48
Would you mind trying out the latest rc from PowerShell gallery?

**Comment by gabriel-samfira** [comment] 2024-09-26 16:49
You can install it with:

```powershell
Install-Module -Name powershell-yaml -AllowPrerelease
```

**Comment by mabaumgartner** [comment] 2024-09-26 20:21
Thank you!  I was able to download and upload as a file into the Azure Automation runtime and that seems to work.  The built-in integration with the powershell gallery I guess was only pulling the 0.4.7 "stable" release.  Much appreciated!

**Comment by gabriel-samfira** [comment] 2024-09-26 20:23
I think I will release it as stable in the morning

**Comment by ThomasKur** [comment] 2024-12-11 07:21
I can confirm, this solved the issue as well on my side. Would be cool to see the RC released. Thanks for your hard work!

**Comment by gabriel-samfira** [comment] 2024-12-13 14:15
> I think I will release it as stable in the morning

Said me on the 26th of September..... I need to get tested for ADHD.

New version has been published: https://www.powershellgallery.com/packages/powershell-yaml/0.4.8
