### ISSUE TITLE
Issue in adding values to list `key`

### ISSUE THREAD

**Issue by nkrishnakishor** [cloudbase/powershell-yaml#90] opened 2022-11-29 07:13 UTC
I'm trying to add value to an existing list but seeing the error as `MethodInvocationException: Exception calling "Add" with "1" argument(s): "Collection was of a fixed size."` 

Below is the yaml file unable to add values under `key`
```
value1:
value2:
  - key:
    - subkey1
    - subkey2
```

Below is the error message 
`MethodInvocationException: Exception calling "Add" with "1" argument(s): "Collection was of a fixed size."`

code to update the value
```
$file = ConvertFrom-Yaml $(Get-Content C:\Users\user\powershell\actualfile.yaml -Raw) -Ordered
$file.instances.services.Add("test3")
```

Expected behaviour
```
$file = ConvertFrom-Yaml $(Get-Content C:\Users\user\powershell\actualfile.yaml -Raw) -Ordered
$file.instances.services.Add("test3")
```
Output of the command `$file.instances.services` should be below
```
subkey1
subkey2
test3
```

**Comment by gabriel-samfira** [comment] 2022-11-29 08:56
Hi @nkrishnakishor !

Could you share a sanitized sample of that file with which I could reproduce the issue?

I tried this:

```powershell
PS /home/gabriel> $data = @"                          
>> value1:          
>> value2:
>>   - key:
>>     - subkey1
>>     - subkey2
>> "@
PS /home/gabriel> $converted = ConvertFrom-Yaml -Ordered $data
PS /home/gabriel> $converted.value2[0].key.Add("asdas")       
PS /home/gabriel> ConvertTo-Yaml $converted      
value1: 
value2:
- key:
  - subkey1
  - subkey2
  - asdas
```

**Comment by gabriel-samfira** [comment] 2022-11-29 09:56
So, this seems to be a ```powershell``` particularity where you can reference keys from inside an array of objects, and powershell just returns an aggregate list of what it finds.

Consider the following example:

```powershell
$data = @"
value1:
value2:
  - key:
    - subkey1
    - subkey2
  - key:
    - another
  - someOtherKey:
    - someOtherSubKey
"@

PS /home/gabriel> $file.value2.GetType()      

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     List`1                                   System.Object

PS /home/gabriel> $file.value2[0].GetType().FullName
System.Collections.Hashtable

PS /home/gabriel> $file = ConvertFrom-Yaml $data                                            
PS /home/gabriel> $file

Name                           Value
----                           -----
value2                         {subkey1 subkey2, another, someOtherSubKey}
value1                         

PS /home/gabriel> $file.value2.key
subkey1
subkey2
another
PS /home/gabriel> $file.value2[0].key
subkey1
subkey2
PS /home/gabriel> $file.value2[1].key
another
PS /home/gabriel> $file.value2[2].someOtherKey
someOtherSubKey
```

The example yaml we have, defines ```values2``` as an array of ```System.Object```. Those objects are in fact a set of ```System.Collections.Hashtable```.

When you try to reference a key by name from an array of objects, ```powershell``` will try to determine which elements from that array has the ```Keys()``` method, and attempts to fetch the requested key from each of those elements. The result is an array consisting of **all** the values from all the elements that have that key defined.

This is why we see an array of:

```powershell
PS /home/gabriel> $file.value2.key
subkey1
subkey2
another
``` 

Where ```another``` is actually part of the second element named ```key```.

To mutate that object, you will need to reference it by it's index number, like so:

```powershell
PS /home/gabriel> $file.value2[0].key.Add("test3")
PS /home/gabriel> $file.value2[0].key
subkey1
subkey2
test3
```

Or as it's defined in your gist:

```powershell
$file.instances[0].services += "test3"
```

Let me know if that works for you.

**Comment by gabriel-samfira** [comment] 2022-11-29 10:07
To clarify a bit more:

The array you get when calling:

```powershell
$file.value2.key
```

Or as it's defined in your example:

```powershell
$file.instances.services
```
does not really exist. It's generated on the fly by ```powershell``` and returned to the shell.

**Comment by gabriel-samfira** [comment] 2022-11-29 13:04
Will close this issue. Feel free to reopen if you think it's necessary.

**Closed by gabriel-samfira** 2022-11-29 13:04 UTC

**Comment by nkrishnakishor** [comment] 2022-11-29 14:50
Thank you very much @gabriel-samfira

**Comment by gabriel-samfira** [comment] 2022-11-29 14:53
My pleasure!
